"""
ClaimGuard AI — Explainable decision report builder (MVP Simulation).

Assembles a structured, human-readable report JSON from a claim, its agent
results and its audit history. Designed to be rendered as a printable report and
exported as JSON.
"""
from __future__ import annotations

import hashlib
from typing import List

from .agent_engine import generate_summary, run_agents
from .risk_engine import FACTORS_BY_KEY, score_claim

DISCLAIMER = (
    "MVP Simulation — This report is generated by explainable, rule-based demo logic "
    "for hackathon demonstration only. It is NOT certified medical adjudication and "
    "does not use real patient data, real PM-JAY/NHCX integration, or a certified fraud "
    "model. Every recommendation requires human-in-the-loop review before any action."
)

HUMAN_IN_LOOP_NOTE = (
    "ClaimGuard AI never auto-settles a claim on its own. The AI produces a risk score "
    "and an explainable recommendation; a qualified human auditor retains full override "
    "authority and makes the final decision."
)


def _output_hash(claim: dict, score: int) -> str:
    """Deterministic, traceable hash of the model/rule output (MVP placeholder)."""
    payload = f"{claim.get('claim_id','')}|{score}|{','.join(sorted((claim.get('signals') or {}).keys()))}"
    return "sha256:" + hashlib.sha256(payload.encode()).hexdigest()[:16]


def build_report(claim: dict, audit_history: List[dict]) -> dict:
    analysis = score_claim(claim)
    agents = run_agents(claim)
    trust_score = 100 - analysis["score"]

    evidence_table = []
    for f in analysis["factors"]:
        if f["active"]:
            evidence_table.append(
                {
                    "signal": f["label"],
                    "category": f["category"],
                    "agent": f["agent"],
                    "risk_contribution": f["contribution"],
                    "detail": f["description"],
                }
            )

    top_reasons = [
        {"reason": f["label"], "contribution": f["contribution"], "detail": f["description"]}
        for f in analysis["top_factors"]
    ]
    if not top_reasons:
        top_reasons = [
            {
                "reason": "No risk signals detected",
                "contribution": 0,
                "detail": "Complete documents, guideline compliant, no fraud flags.",
            }
        ]

    auditor_notes = [
        {
            "action": a["action"],
            "note": a["note"],
            "role": a["user_role"],
            "timestamp": a["timestamp"],
        }
        for a in audit_history
        if a.get("note")
    ]

    return {
        "claim_id": claim.get("claim_id"),
        "generated_for": claim.get("beneficiary_id"),
        "hospital": claim.get("hospital_name"),
        "treatment_package": claim.get("treatment_package"),
        "claim_amount": claim.get("claim_amount"),
        "summary": claim.get("ai_summary") or generate_summary(claim),
        "claim_trust_score": trust_score,
        "risk_score": analysis["score"],
        "risk_category": analysis["category"],
        "fraud_risk_level": analysis["fraud_risk"],
        "medical_necessity": analysis["medical_necessity"],
        "document_completeness": analysis["document_completeness"],
        "stg_compliance": analysis["stg_compliance"],
        "recommended_action": analysis["recommended_action"],
        "status": claim.get("status"),
        "evidence_table": evidence_table,
        "top_risk_reasons": top_reasons,
        "agents": agents,
        "auditor_notes": auditor_notes,
        "audit_trail": audit_history,
        "model_rule_explanation": (
            "Risk score is the capped sum of weighted, rule-based signals "
            f"({analysis['raw_total']} raw → {analysis['score']} capped at 100). "
            "Each signal weight is fixed and auditable; no opaque model is used in this MVP."
        ),
        "output_hash": _output_hash(claim, analysis["score"]),
        "human_in_loop_note": HUMAN_IN_LOOP_NOTE,
        "disclaimer": DISCLAIMER,
    }
